language: go
go:
  - "1.9"
  - "1.10"
  - "tip"
install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep ensure
script:
  - go test -coverpkg=./... -race -coverprofile=coverage.txt -covermode=atomic
after_success:
  - bash <(curl -s https://codecov.io/bash)
