[[constraint]]
  name = "github.com/fsm/cache-store"
  version = "v2.0.0"

[[constraint]]
  name = "github.com/fsm/cli"
  version = "v2.0.1"

[[constraint]]
  name = "github.com/fsm/emitable"
  version = "1.0.0"

[[constraint]]
  name = "github.com/fsm/fsm"
  version = "v2.0.0"

[[constraint]]
  name = "github.com/fsm/test"
  version = "v2.0.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "v1.2.1"
